FROM python:3.10-slim

WORKDIR /app

# Dependencias del sistema para OpenCV
RUN apt-get update && \
    apt-get install -y ffmpeg libsm6 libxext6 && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "reconocimiento.py"]
